packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  better-auth: 1.4.10
  drizzle-orm: ^0.45.0
  '@orpc/client': ^1.13.2
  '@orpc/experimental-pino': ^1.13.2
  '@orpc/openapi': ^1.13.2
  '@orpc/server': ^1.13.2
  '@orpc/tanstack-query': ^1.13.2
  '@orpc/zod': ^1.13.2
  '@types/node': ^22.13.11
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  dotenv: ^17.2.2
  pino: ^10.1.0
  pino-pretty: ^13.1.3
  react: ^19.2.0
  react-dom: ^19.2.0
  redis: ^5.10.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vitest: ^4.0.16
  zod: ^4.1.13
