/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as MainTutorialsRouteImport } from './routes/_main/tutorials'
import { Route as MainTermsRouteImport } from './routes/_main/terms'
import { Route as MainResetPasswordRouteImport } from './routes/_main/reset-password'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainPrivacyRouteImport } from './routes/_main/privacy'
import { Route as MainPostSearchRouteImport } from './routes/_main/post-search'
import { Route as MainLegalRouteImport } from './routes/_main/legal'
import { Route as MainForgotPasswordRouteImport } from './routes/_main/forgot-password'
import { Route as MainComicSearchRouteImport } from './routes/_main/comic-search'
import { Route as MainChronosRouteImport } from './routes/_main/chronos'
import { Route as MainAuthRouteImport } from './routes/_main/auth'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTermsIndexRouteImport } from './routes/admin/terms/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminComicsIndexRouteImport } from './routes/admin/comics/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminTermsCreateRouteImport } from './routes/admin/terms/create'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminExtrasWeeklyRouteImport } from './routes/admin/extras/weekly'
import { Route as AdminExtrasTutorialsRouteImport } from './routes/admin/extras/tutorials'
import { Route as AdminComicsCreateRouteImport } from './routes/admin/comics/create'
import { Route as MainUserIdRouteImport } from './routes/_main/user.$id'
import { Route as MainPostIdRouteImport } from './routes/_main/post.$id'
import { Route as MainComicIdRouteImport } from './routes/_main/comic.$id'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTutorialsRoute = MainTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTermsRoute = MainTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPostSearchRoute = MainPostSearchRouteImport.update({
  id: '/post-search',
  path: '/post-search',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLegalRoute = MainLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainForgotPasswordRoute = MainForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainComicSearchRoute = MainComicSearchRouteImport.update({
  id: '/comic-search',
  path: '/comic-search',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainChronosRoute = MainChronosRouteImport.update({
  id: '/chronos',
  path: '/chronos',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAuthRoute = MainAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTermsIndexRoute = AdminTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsIndexRoute = AdminComicsIndexRouteImport.update({
  id: '/comics/',
  path: '/comics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTermsCreateRoute = AdminTermsCreateRouteImport.update({
  id: '/terms/create',
  path: '/terms/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasWeeklyRoute = AdminExtrasWeeklyRouteImport.update({
  id: '/extras/weekly',
  path: '/extras/weekly',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasTutorialsRoute = AdminExtrasTutorialsRouteImport.update({
  id: '/extras/tutorials',
  path: '/extras/tutorials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsCreateRoute = AdminComicsCreateRouteImport.update({
  id: '/comics/create',
  path: '/comics/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainUserIdRoute = MainUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPostIdRoute = MainPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainComicIdRoute = MainComicIdRouteImport.update({
  id: '/comic/$id',
  path: '/comic/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/posts/edit/$id',
  path: '/posts/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/auth': typeof MainAuthRoute
  '/chronos': typeof MainChronosRoute
  '/comic-search': typeof MainComicSearchRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/legal': typeof MainLegalRoute
  '/post-search': typeof MainPostSearchRoute
  '/privacy': typeof MainPrivacyRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/terms': typeof MainTermsRoute
  '/tutorials': typeof MainTutorialsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/comic/$id': typeof MainComicIdRoute
  '/post/$id': typeof MainPostIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/comics': typeof AdminComicsIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/terms': typeof AdminTermsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/auth': typeof MainAuthRoute
  '/chronos': typeof MainChronosRoute
  '/comic-search': typeof MainComicSearchRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/legal': typeof MainLegalRoute
  '/post-search': typeof MainPostSearchRoute
  '/privacy': typeof MainPrivacyRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/terms': typeof MainTermsRoute
  '/tutorials': typeof MainTutorialsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/comic/$id': typeof MainComicIdRoute
  '/post/$id': typeof MainPostIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/comics': typeof AdminComicsIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/terms': typeof AdminTermsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/auth': typeof MainAuthRoute
  '/_main/chronos': typeof MainChronosRoute
  '/_main/comic-search': typeof MainComicSearchRoute
  '/_main/forgot-password': typeof MainForgotPasswordRoute
  '/_main/legal': typeof MainLegalRoute
  '/_main/post-search': typeof MainPostSearchRoute
  '/_main/privacy': typeof MainPrivacyRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/terms': typeof MainTermsRoute
  '/_main/tutorials': typeof MainTutorialsRoute
  '/api/health': typeof ApiHealthRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_main/comic/$id': typeof MainComicIdRoute
  '/_main/post/$id': typeof MainPostIdRoute
  '/_main/user/$id': typeof MainUserIdRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/comics/': typeof AdminComicsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/terms/': typeof AdminTermsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/about'
    | '/auth'
    | '/chronos'
    | '/comic-search'
    | '/forgot-password'
    | '/legal'
    | '/post-search'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/terms'
    | '/tutorials'
    | '/api/health'
    | '/'
    | '/admin/'
    | '/comic/$id'
    | '/post/$id'
    | '/user/$id'
    | '/admin/comics/create'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/posts/create'
    | '/admin/terms/create'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/comics'
    | '/admin/posts'
    | '/admin/terms'
    | '/admin/users'
    | '/admin/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth'
    | '/chronos'
    | '/comic-search'
    | '/forgot-password'
    | '/legal'
    | '/post-search'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/terms'
    | '/tutorials'
    | '/api/health'
    | '/'
    | '/admin'
    | '/comic/$id'
    | '/post/$id'
    | '/user/$id'
    | '/admin/comics/create'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/posts/create'
    | '/admin/terms/create'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/comics'
    | '/admin/posts'
    | '/admin/terms'
    | '/admin/users'
    | '/admin/posts/edit/$id'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/_main/about'
    | '/_main/auth'
    | '/_main/chronos'
    | '/_main/comic-search'
    | '/_main/forgot-password'
    | '/_main/legal'
    | '/_main/post-search'
    | '/_main/privacy'
    | '/_main/profile'
    | '/_main/reset-password'
    | '/_main/terms'
    | '/_main/tutorials'
    | '/api/health'
    | '/_main/'
    | '/admin/'
    | '/_main/comic/$id'
    | '/_main/post/$id'
    | '/_main/user/$id'
    | '/admin/comics/create'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/posts/create'
    | '/admin/terms/create'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/comics/'
    | '/admin/posts/'
    | '/admin/terms/'
    | '/admin/users/'
    | '/admin/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/tutorials': {
      id: '/_main/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof MainTutorialsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/terms': {
      id: '/_main/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainTermsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/privacy': {
      id: '/_main/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainPrivacyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/post-search': {
      id: '/_main/post-search'
      path: '/post-search'
      fullPath: '/post-search'
      preLoaderRoute: typeof MainPostSearchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/legal': {
      id: '/_main/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof MainLegalRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/forgot-password': {
      id: '/_main/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof MainForgotPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/comic-search': {
      id: '/_main/comic-search'
      path: '/comic-search'
      fullPath: '/comic-search'
      preLoaderRoute: typeof MainComicSearchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/chronos': {
      id: '/_main/chronos'
      path: '/chronos'
      fullPath: '/chronos'
      preLoaderRoute: typeof MainChronosRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/auth': {
      id: '/_main/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof MainAuthRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/terms/': {
      id: '/admin/terms/'
      path: '/terms'
      fullPath: '/admin/terms'
      preLoaderRoute: typeof AdminTermsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/': {
      id: '/admin/comics/'
      path: '/comics'
      fullPath: '/admin/comics'
      preLoaderRoute: typeof AdminComicsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/terms/create': {
      id: '/admin/terms/create'
      path: '/terms/create'
      fullPath: '/admin/terms/create'
      preLoaderRoute: typeof AdminTermsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/weekly': {
      id: '/admin/extras/weekly'
      path: '/extras/weekly'
      fullPath: '/admin/extras/weekly'
      preLoaderRoute: typeof AdminExtrasWeeklyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/tutorials': {
      id: '/admin/extras/tutorials'
      path: '/extras/tutorials'
      fullPath: '/admin/extras/tutorials'
      preLoaderRoute: typeof AdminExtrasTutorialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/create': {
      id: '/admin/comics/create'
      path: '/comics/create'
      fullPath: '/admin/comics/create'
      preLoaderRoute: typeof AdminComicsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/user/$id': {
      id: '/_main/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof MainUserIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/post/$id': {
      id: '/_main/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof MainPostIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/comic/$id': {
      id: '/_main/comic/$id'
      path: '/comic/$id'
      fullPath: '/comic/$id'
      preLoaderRoute: typeof MainComicIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/posts/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainAuthRoute: typeof MainAuthRoute
  MainChronosRoute: typeof MainChronosRoute
  MainComicSearchRoute: typeof MainComicSearchRoute
  MainForgotPasswordRoute: typeof MainForgotPasswordRoute
  MainLegalRoute: typeof MainLegalRoute
  MainPostSearchRoute: typeof MainPostSearchRoute
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainProfileRoute: typeof MainProfileRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainTermsRoute: typeof MainTermsRoute
  MainTutorialsRoute: typeof MainTutorialsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainComicIdRoute: typeof MainComicIdRoute
  MainPostIdRoute: typeof MainPostIdRoute
  MainUserIdRoute: typeof MainUserIdRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainAuthRoute: MainAuthRoute,
  MainChronosRoute: MainChronosRoute,
  MainComicSearchRoute: MainComicSearchRoute,
  MainForgotPasswordRoute: MainForgotPasswordRoute,
  MainLegalRoute: MainLegalRoute,
  MainPostSearchRoute: MainPostSearchRoute,
  MainPrivacyRoute: MainPrivacyRoute,
  MainProfileRoute: MainProfileRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainTermsRoute: MainTermsRoute,
  MainTutorialsRoute: MainTutorialsRoute,
  MainIndexRoute: MainIndexRoute,
  MainComicIdRoute: MainComicIdRoute,
  MainPostIdRoute: MainPostIdRoute,
  MainUserIdRoute: MainUserIdRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminComicsCreateRoute: typeof AdminComicsCreateRoute
  AdminExtrasTutorialsRoute: typeof AdminExtrasTutorialsRoute
  AdminExtrasWeeklyRoute: typeof AdminExtrasWeeklyRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminTermsCreateRoute: typeof AdminTermsCreateRoute
  AdminComicsIndexRoute: typeof AdminComicsIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminTermsIndexRoute: typeof AdminTermsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminComicsCreateRoute: AdminComicsCreateRoute,
  AdminExtrasTutorialsRoute: AdminExtrasTutorialsRoute,
  AdminExtrasWeeklyRoute: AdminExtrasWeeklyRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminTermsCreateRoute: AdminTermsCreateRoute,
  AdminComicsIndexRoute: AdminComicsIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminTermsIndexRoute: AdminTermsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
